name: anchor-test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-anchor-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: staccDOTsol/anchor-test@v2.1
        with:
            anchor-version: '0.28.0'
            solana-cli-version: '1.16.0'
